version: '3.1'

services:

  db:
    image: mysql
    container_name: 'imdb-db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - imdb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  spring-boot:
    image: melihcskn/test
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/imdb
      - spring.datasource.password=password
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  imdb_data:

networks:
  backend-network:
      