services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbitmq_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
